drop TABLE public."Blog";
drop TABLE public."Comment";


CREATE TABLE public."Blog"
(
  ID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  creator varchar(100),
  title varchar(100),
  text varchar(100)
);



CREATE TABLE public."Comment"
(
  ID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  blog_id int,
  comment varchar(100)
);
